namespace Eindopdracht_CSharp.Enums;

public enum Species
{
    // Generated by ChatGPT-4o

    // Mammals
    Lion,
    Tiger,
    Elephant,
    Giraffe,
    Zebra,
    Kangaroo,
    Gorilla,
    Panda,
    Dolphin,

    // Birds
    Eagle,
    Parrot,
    Penguin,
    Flamingo,
    Owl,
    Peacock,

    // Reptiles
    Crocodile,
    Alligator,
    KomodoDragon,
    Snake,
    Tortoise,
    Iguana,

    // Amphibians
    Frog,
    Salamander,
    Toad,

    // Fish
    Shark,
    Clownfish,
    Stingray,
    Tuna,
    Seahorse,

    // Insects
    Butterfly,
    Bee,
    Ant,
    Beetle,
    Dragonfly,

    // Other
    Octopus,
    Jellyfish,
    Crab,
    Starfish
}