// <auto-generated />
using Eindopdracht_CSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eindopdracht_CSharp.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    partial class ZooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityPattern")
                        .HasColumnType("int");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DietaryClass")
                        .HasColumnType("int");

                    b.Property<int?>("EnclosureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SecurityRequirement")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<double>("SpaceRequirement")
                        .HasColumnType("float");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EnclosureId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityPattern = 0,
                            CategoryId = 4,
                            DietaryClass = 3,
                            EnclosureId = 12,
                            Name = "Okey",
                            SecurityRequirement = 0,
                            Size = 5,
                            SpaceRequirement = 3.7053918212301982,
                            Species = 24
                        },
                        new
                        {
                            Id = 2,
                            ActivityPattern = 0,
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 14,
                            Name = "Bernice",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 1.0284269840285813,
                            Species = 25
                        },
                        new
                        {
                            Id = 3,
                            ActivityPattern = 2,
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 3,
                            Name = "Paris",
                            SecurityRequirement = 2,
                            Size = 2,
                            SpaceRequirement = 1.6535331778675593,
                            Species = 35
                        },
                        new
                        {
                            Id = 4,
                            ActivityPattern = 2,
                            CategoryId = 1,
                            DietaryClass = 1,
                            EnclosureId = 9,
                            Name = "Lane",
                            SecurityRequirement = 1,
                            Size = 2,
                            SpaceRequirement = 2.8399000803108279,
                            Species = 7
                        },
                        new
                        {
                            Id = 5,
                            ActivityPattern = 1,
                            CategoryId = 2,
                            DietaryClass = 1,
                            EnclosureId = 14,
                            Name = "Davion",
                            SecurityRequirement = 2,
                            Size = 1,
                            SpaceRequirement = 9.5525154581296725,
                            Species = 15
                        },
                        new
                        {
                            Id = 6,
                            ActivityPattern = 0,
                            CategoryId = 3,
                            DietaryClass = 4,
                            EnclosureId = 10,
                            Name = "Ryleigh",
                            SecurityRequirement = 1,
                            Size = 1,
                            SpaceRequirement = 18.479984319098158,
                            Species = 32
                        },
                        new
                        {
                            Id = 7,
                            ActivityPattern = 0,
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 9,
                            Name = "Della",
                            SecurityRequirement = 2,
                            Size = 2,
                            SpaceRequirement = 1.6570568238059913,
                            Species = 16
                        },
                        new
                        {
                            Id = 8,
                            ActivityPattern = 1,
                            CategoryId = 1,
                            DietaryClass = 0,
                            EnclosureId = 14,
                            Name = "Nolan",
                            SecurityRequirement = 2,
                            Size = 2,
                            SpaceRequirement = 12.018208824198663,
                            Species = 25
                        },
                        new
                        {
                            Id = 9,
                            ActivityPattern = 0,
                            CategoryId = 5,
                            DietaryClass = 1,
                            EnclosureId = 15,
                            Name = "Sylvan",
                            SecurityRequirement = 2,
                            Size = 5,
                            SpaceRequirement = 8.7697275484783557,
                            Species = 29
                        },
                        new
                        {
                            Id = 10,
                            ActivityPattern = 1,
                            CategoryId = 5,
                            DietaryClass = 3,
                            EnclosureId = 3,
                            Name = "Eloisa",
                            SecurityRequirement = 0,
                            Size = 2,
                            SpaceRequirement = 2.7571552086148716,
                            Species = 34
                        });
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mammals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Birds"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Reptiles"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aquatic Animals"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Insects"
                        });
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Enclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Climate")
                        .HasColumnType("int");

                    b.Property<int>("HabitatType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int?>("ZooId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZooId");

                    b.HasIndex("Id", "Name")
                        .IsUnique();

                    b.ToTable("Enclosures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Climate = 1,
                            HabitatType = 1,
                            Name = "Industrial",
                            SecurityLevel = 1,
                            Size = 198.0,
                            ZooId = 4
                        },
                        new
                        {
                            Id = 2,
                            Climate = 0,
                            HabitatType = 4,
                            Name = "Movies & Movies",
                            SecurityLevel = 2,
                            Size = 289.0,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 3,
                            Climate = 1,
                            HabitatType = 2,
                            Name = "Toys",
                            SecurityLevel = 1,
                            Size = 309.0,
                            ZooId = 5
                        },
                        new
                        {
                            Id = 4,
                            Climate = 2,
                            HabitatType = 1,
                            Name = "Electronics, Outdoors & Sports",
                            SecurityLevel = 0,
                            Size = 160.0,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 5,
                            Climate = 2,
                            HabitatType = 1,
                            Name = "Tools",
                            SecurityLevel = 1,
                            Size = 679.0,
                            ZooId = 3
                        },
                        new
                        {
                            Id = 6,
                            Climate = 0,
                            HabitatType = 1,
                            Name = "Garden & Computers",
                            SecurityLevel = 2,
                            Size = 742.0,
                            ZooId = 5
                        },
                        new
                        {
                            Id = 7,
                            Climate = 2,
                            HabitatType = 4,
                            Name = "Health & Sports",
                            SecurityLevel = 0,
                            Size = 877.0,
                            ZooId = 5
                        },
                        new
                        {
                            Id = 8,
                            Climate = 0,
                            HabitatType = 8,
                            Name = "Jewelery, Music & Garden",
                            SecurityLevel = 1,
                            Size = 895.0,
                            ZooId = 3
                        },
                        new
                        {
                            Id = 9,
                            Climate = 1,
                            HabitatType = 2,
                            Name = "Shoes",
                            SecurityLevel = 1,
                            Size = 849.0,
                            ZooId = 5
                        },
                        new
                        {
                            Id = 10,
                            Climate = 1,
                            HabitatType = 4,
                            Name = "Kids",
                            SecurityLevel = 0,
                            Size = 937.0,
                            ZooId = 3
                        },
                        new
                        {
                            Id = 11,
                            Climate = 0,
                            HabitatType = 8,
                            Name = "Clothing, Music & Computers",
                            SecurityLevel = 1,
                            Size = 885.0,
                            ZooId = 1
                        },
                        new
                        {
                            Id = 12,
                            Climate = 0,
                            HabitatType = 8,
                            Name = "Jewelery",
                            SecurityLevel = 2,
                            Size = 784.0,
                            ZooId = 5
                        },
                        new
                        {
                            Id = 13,
                            Climate = 1,
                            HabitatType = 2,
                            Name = "Books",
                            SecurityLevel = 2,
                            Size = 770.0,
                            ZooId = 2
                        },
                        new
                        {
                            Id = 14,
                            Climate = 1,
                            HabitatType = 8,
                            Name = "Baby",
                            SecurityLevel = 0,
                            Size = 972.0,
                            ZooId = 5
                        },
                        new
                        {
                            Id = 15,
                            Climate = 1,
                            HabitatType = 1,
                            Name = "Jewelery",
                            SecurityLevel = 1,
                            Size = 535.0,
                            ZooId = 4
                        });
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Zoo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zoos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lehner - Weber"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stoltenberg - McClure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Russel - Bashirian"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ullrich, Cummings and Brakus"
                        },
                        new
                        {
                            Id = 5,
                            Name = "VonRueden - West"
                        });
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Animal", b =>
                {
                    b.HasOne("Eindopdracht_CSharp.Models.Animal", null)
                        .WithMany("Prey")
                        .HasForeignKey("AnimalId");

                    b.HasOne("Eindopdracht_CSharp.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eindopdracht_CSharp.Models.Enclosure", "Enclosure")
                        .WithMany("Animals")
                        .HasForeignKey("EnclosureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Enclosure");
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Enclosure", b =>
                {
                    b.HasOne("Eindopdracht_CSharp.Models.Zoo", "Zoo")
                        .WithMany("Enclosures")
                        .HasForeignKey("ZooId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Animal", b =>
                {
                    b.Navigation("Prey");
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Enclosure", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Eindopdracht_CSharp.Models.Zoo", b =>
                {
                    b.Navigation("Enclosures");
                });
#pragma warning restore 612, 618
        }
    }
}
